name: CI

on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-20.04

    steps:
    
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Update
      run: sudo apt-get update

    - name: Install OpenGL dev
      run: sudo apt-get install -y xorg-dev libglu1-mesa-dev mesa-common-dev

    - name: Install X11 dev
      run: sudo apt-get install -y libx11-dev libxcursor-dev libxinerama-dev

    - name: Install ALSA dev
      run: sudo apt-get install -y libasound2-dev

    - name: Install PulseAudio dev
      run: sudo apt-get install -y libpulse-dev

    - name: Install Pango dev
      run: sudo apt-get install -y libpango1.0-dev

    - name: Install Wayland
      run: sudo apt-get install -y libwayland-dev wayland-protocols libdbus-1-dev libxkbcommon-dev libegl-dev libgtk-3-dev

    - name: Install openssl
      run: sudo apt-get install -y openssl
      
    - name: Install ninja-build
      run: sudo apt-get install -y ninja-build
      
    - name: Install gettext
      run: sudo apt-get install -y gettext
      
    - name: Install python dependencies
      run: sudo apt-get install -y libssl-dev libffi-dev

    - name: Build mrv2
      run: >
        ./runme_nolog.sh -t package && ./bin/upload_sourceforge.sh
